import glob
import pandas as pd
import snakemake.utils

# User-specified dataset-specific config file
dataset_config_file = config.get("dataset_config_file", None)

# Load fixed config parameters
configfile: "config/params.yaml"

# Check if the dataset-specific config file is provided
if dataset_config_file is not None:
    # Load dataset-specific parameters
    configfile: dataset_config_file

# include: 'rules/prepare.smk'
# include: 'rules/structure.smk'
# include: 'rules/sequence.smk'
include: 'rules/checks.smk'
include: 'rules/common.smk'
include: 'rules/analysis.smk'


input_table = pd.read_csv(config['taxids'], sep='\t')
input_table.columns = ['uniprot', 'taxid', 'mnemo']
input_dict = input_table.set_index('uniprot').T.to_dict()

codes = list(input_table['uniprot'])

homodir=config['outdir']+'homology/'+config['homology_dataset']
outdir=config['outdir']+'phylogeny/'+config['phylo_dataset']

# possible combinations:
combinations_codes_str=[x+"_"+y for x in codes for y in codes]

# for the plots you need to work a bit on adapting to new nonphylome method
plots = ["discordance"] # "runtime", "astral_pro", "trees", "discordance", "examples", "distance"

rule all:
    input:
        expand(outdir+"/plots/{seed}_{plot}.pdf", seed=config['seed'], plot=plots),
        expand(outdir+"/plots/{seed}_foldmason", seed=config['seed']),
        expand(outdir+"/trees/{seed}_{mode}_trees.txt", seed=config['seed'], mode=config["modes"])
        # expand(outdir+"/reco/{seed}_notung.tsv", seed=config['seed']),
        # expand(outdir+"/trees/{seed}_mltrees.txt", seed=config['seed'])

