import glob
import pandas as pd
import snakemake.utils

# User-specified dataset-specific config file
dataset_config_file = config.get("dataset_config_file", None)

# Load fixed config parameters
configfile: "config/params.yaml"

# Check if the dataset-specific config file is provided
if dataset_config_file is not None:
    # Load dataset-specific parameters
    configfile: dataset_config_file

include: 'rules/prepare.smk'
include: 'rules/structure.smk'
include: 'rules/sequence.smk'
include: 'rules/checks.smk'
include: 'rules/common.smk'
include: 'rules/analysis.smk'

input_table = pd.read_csv(config['input_table_file'], header=None, sep='\t')
input_table.columns = ['uniprot', 'taxid', 'count1', 'count2', 'count3', 'genome', 'source', 'species', 'mnemo']
input_dict = input_table.set_index('uniprot').T.to_dict()

codes = list(input_table['uniprot'])

outdir=config['outdir']+config['dataset']

# possible combinations:
combinations_codes_str=[x+"_"+y for x in codes for y in codes]

plots = ["homology", "saturation", "runtime", "astral_pro", "trees", "discordance", "singletons"]

rule all:
    input:
        outdir+'/db/db_num.tsv',
        expand(outdir+"/plots/{seed}_{plot}.pdf", seed=config['seed'], plot=plots)
