# Overall this snakemake file is a modified version of the original one, which keeps the relevant steps but gets rid of the non applicable stuff (Astral and Notung support, blast vs foldseek and much more).

import glob
import pandas as pd
import snakemake.utils

# Load fixed config parameters
configfile: "config/params.yaml"

# get the input directory
input_dir = config["input_dir"]
output_dir = config["outdir"]
combinations_ML = config["combinations_ML"]

# Here only the rule make_fastas that exctracts the fast sequence from pdb file is of interest
# include: 'rules/prepare.smk'
# This contains the rules for foldseek
include: 'rules/structure.smk'
# This constructs blast databases used for searching, unclear if i need this
# include: 'rules/sequence.smk'
# Some stuff here might be useful, some not
# include: 'rules/checks.smk'
# Makes alignments and actually runs the trees
include: 'rules/common.smk'
# mainly for plotting, probably not needed
# include: 'rules/analysis.smk'
include: 'rules/download_data.smk'

rule all:
    input:
        # download structures, wait for it to be done
        f"{output_dir}/done.txt",

        # Filtered homologs (if needed)
        # f"{output_dir}/foldseek/results/filtered_homologs.tsv",

        # Foldmason Report
        f"{output_dir}/foldtree/foldmason_report/foldmason_alignment_3Di.html",

        # ✅ FoldTree Results
        f"{output_dir}/foldtree/foldtree_3Di_FT.nwk",
        
        # fastME Results
        #f"{output_dir}/fastME/FM.nwk",

        # IQ-TREE results for each alphabet and model
        f"{output_dir}/iqtree/aa/LG.iqtree",
        expand(f"{output_dir}/iqtree/3Di/{{model}}.nwk", model=["3Di", "AF"]),  # 3Di and AF for 3Di alphabet

        # Partitioned IQ-TREE results combining LG with both 3Di and AF
        expand(f"{output_dir}/iqtree_partitioned/LG_{{combs_3di}}.nwk",
               combs_3di=["3Di", "AF"])

